# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
        additional_dependencies: [
            "flake8-print==3.1.4"
        ]
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    -   id: isort
        args: [-rc]
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.0
    hooks:
    -   id: markdownlint
        args: [--fix]
